export default [
    {
        'chat_id':0,
        'game_id':2,
        'team_index':0,
        'chat_type':'team',
        'messages':[
            {
                'message_id':0,
                'content':'hello',
                'user_name':'user1',
                'team_index':0,
                'user_id':1
            },
            {
                'message_id':1,
                'content':'helldfo',
                'user_name':'user0',
                'team_index':0,
                'user_id':0
            },
            {
                'message_id':2,
                'content':'hedsfllo',
                'user_name':'user2',
                'team_index':0,
                'user_id':2
            },
            {
                'message_id':3,
                'content':'helldfsfo',
                'user_name':'user3',
                'team_index':0,
                'user_id':3
            },
            {
                'message_id':4,
                'content':'hellsffo',
                'user_name':'user4',
                'team_index':0,
                'user_id':4
            },
            {
                'message_id':5,
                'content':'hellsdfo',
                'user_name':'user3',
                'team_index':0,
                'user_id':3
            },
        ]
    },
    {
        'chat_id':1,
        'game_id':2,
        'team_index':2,
        'chat_type':'all',
        'messages':[
            {
                'message_id':0,
                'content':'all',
                'user_name':'user1',
                'team_index':1,
                'user_id':1
            },
            {
                'message_id':1,
                'content':'all242',
                'user_name':'user0',
                'team_index':0,
                'user_id':0
            },
            {
                'message_id':2,
                'content':'all2325',
                'user_name':'user2',
                'team_index':0,
                'user_id':2
            },
            {
                'message_id':3,
                'content':'helldfsfo',
                'user_name':'user3',
                'user_id':3,
                'team_index':1,
            },
            {
                'message_id':4,
                'content':'hellsffo',
                'user_name':'user4',
                'team_index':0,
                'user_id':4
            },
            {
                'message_id':5,
                'content':'hellsdfo',
                'team_index':2,
                'user_name':'teacher',
                'user_id':3
            },
        ]
    }
]