export default [
    {
        'team_id':0,
        'game_id':2,
        'team_index':0,
        'team_name':'teamA',
        'members':[
            {
                'id':0,
                'user_id':0,
                'user_name':'user0',
                'score':1325231,
            },
            {
                'id':1,
                'user_id':1,
                'user_name':'user1',
                'score':13231,
            }
        ],
        'max_member_count':4
    },
    {
        'team_id':1,
        'game_id':2,
        'team_index':1,
        'team_name':'teamB',
        'members':[
            {
                'id':2,
                'user_id':2,
                'user_name':'user2',
                'score':13231,
            },
            {
                'id':3,
                'user_id':3,
                'user_name':'user3',
                'score':231,
            }
        ],
        'max_member_count':4
    }
]