export default [
    {
        'user_id':0,
        'user_name':'user0',
        'password':'0'
    },
    {
        'user_id':1,
        'user_name':'user1',
        'password':'1'
    },
    {
        'user_id':2,
        'user_name':'user2',
        'password':'2'
    },
    {
        'user_id':3,
        'user_name':'user3',
        'password':'3'
    },
    {
        'user_id':4,
        'user_name':'user4',
        'password':'4'
    },
    {
        'user_id':5,
        'user_name':'user5',
        'password':'5'
    },
    
]